/**
 * Synthea hastalıkları için rubrik / ideal yol iskeletleri (granüler test key'leri).
 * Etiketler ve eğitim içeriği Türkçedir. Synthea objektif veri (lab/vital/dx)
 * sağlar; bu şablonlar OSCE rubrik iskeletidir.
 */

import { CdmRubrikAksiyon } from "../../cdm/types";

export interface SyntheaRubricTemplate {
  beklenenSorular: CdmRubrikAksiyon[];
  beklenenTestler: CdmRubrikAksiyon[];
  gereksizTestler: CdmRubrikAksiyon[];
  redFlagler: CdmRubrikAksiyon[];
  idealYol: string[];
  egitimNotu: string;
  anaSikayetStub: string;
  ozetStub: string[];
}

const DEFAULT_TEMPLATE: SyntheaRubricTemplate = {
  beklenenSorular: [
    { key: "CHIEF_COMPLAINT", etiket: "Ana şikayet", aciklama: "Başlangıç ve niteliği", kategori: "Sikayet" },
    { key: "HISTORY_OF_PRESENT", etiket: "Öykü", aciklama: "Zaman ve tetikleyiciler", kategori: "HPI" },
    { key: "PAST_MEDICAL", etiket: "Özgeçmiş", aciklama: "Kronik hastalıklar", kategori: "Ozgecmis" },
    { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Kullandığı ilaçlar", kategori: "Ilac" },
    { key: "FAMILY_HISTORY", etiket: "Aile öyküsü", aciklama: "İlgili kalıtım", kategori: "Aile" },
    { key: "SOCIAL_HISTORY", etiket: "Sosyal öykü", aciklama: "Sigara, alkol", kategori: "Sosyal" },
  ],
  beklenenTestler: [
    { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
    { key: "WBC", etiket: "Lökosit", aciklama: "Hemogram" },
    { key: "PLT", etiket: "Trombosit", aciklama: "Hemogram" },
    { key: "GLUKOZ", etiket: "Glukoz", aciklama: "Metabolik panel" },
    { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
    { key: "NA", etiket: "Sodyum", aciklama: "Elektrolitler" },
    { key: "K", etiket: "Potasyum", aciklama: "Elektrolitler" },
  ],
  gereksizTestler: [],
  redFlagler: [
    { key: "HEMODYNAMIC", etiket: "Hemodinamik bozulma", aciklama: "Hipotansiyon, şok" },
  ],
  idealYol: [
    "1. Havayolu, solunum, dolaşım ve vital bulguları değerlendir.",
    "2. Odaklı öykü al ve ilaçları gözden geçir.",
    "3. Hedefe yönelik fizik muayene yap.",
    "4. Temel laboratuvar paneli iste (hemogram, metabolik, böbrek).",
    "5. Hastalığa özgü görüntüleme veya biyobelirteçleri düşün.",
    "6. Ayırıcı tanı muhakemesiyle tanıyı netleştir.",
    "7. Tedaviyi başlat ve izlemi planla.",
  ],
  egitimNotu: "Synthea kaynaklı sentetik eğitim vakası. Klinik verileri ilişkilendir; karar vermeden önce bir uzmana danış.",
  anaSikayetStub: "Genel yakınma",
  ozetStub: ["Synthea kaynaklı sentetik hasta.", "Laboratuvar ve vital verileri kaynak kayıttan.", "Yalnızca eğitim amaçlı."],
};

export const SYNTHEA_DISEASE_RUBRIC_TEMPLATES: Record<string, SyntheaRubricTemplate> = {
  stemi: {
    beklenenSorular: [
      { key: "CHEST_PAIN_CHARACTER", etiket: "Göğüs ağrısı karakteri", aciklama: "Bası, sıkışma?", kategori: "Sikayet" },
      { key: "RADIATION", etiket: "Yayılım", aciklama: "Kola, çeneye?", kategori: "Sikayet" },
      { key: "ONSET", etiket: "Başlangıç", aciklama: "Ani mi, kademeli mi", kategori: "HPI" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Eforla mı?", kategori: "Sikayet" },
      { key: "CARDIAC_RISK", etiket: "KV risk faktörleri", aciklama: "HT, DM, sigara", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Antitrombosit, nitrat", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "TROPONIN", etiket: "Troponin", aciklama: "Miyokart hasarı" },
      { key: "EKG", etiket: "EKG (12 derivasyon)", aciklama: "ST elevasyonu" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
      { key: "NA", etiket: "Sodyum", aciklama: "Elektrolitler" },
      { key: "K", etiket: "Potasyum", aciklama: "Elektrolitler" },
    ],
    gereksizTestler: [{ key: "MAMOGRAFI", etiket: "Mamografi", aciklama: "Akut göğüs ağrısında yersiz" }],
    redFlagler: [
      { key: "HEMODYNAMIC", etiket: "Hemodinamik bozulma", aciklama: "Şok, aritmi" },
      { key: "ONGOING_CHEST_PAIN", etiket: "Devam eden göğüs ağrısı", aciklama: "Yaşamı tehdit eden" },
    ],
    idealYol: [
      "1. ABC ve monitörizasyon; 12 derivasyon EKG'yi hemen çek.",
      "2. Troponin ve temel laboratuvarı iste.",
      "3. Reperfüzyon kontrendikasyonlarını değerlendir.",
      "4. Protokole göre antitrombosit ve antikoagülasyon uygula.",
      "5. Acil reperfüzyon (PCI veya tromboliz) için sevk et.",
      "6. Aritmi ve hemodinamik bozulmayı izle.",
      "7. İkincil koruma ve kardiyoloji takibini planla.",
    ],
    egitimNotu: "STEMI: ST elevasyonu + klinik. Zaman kritiktir; reperfüzyon geciktirilmemelidir.",
    anaSikayetStub: "Akut göğüs ağrısı",
    ozetStub: ["Sıkıştırıcı göğüs ağrısı", "Terleme ve nefes darlığı olabilir", "KV risk faktörleri sık"],
  },
  nstemi: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "CHEST_PAIN", etiket: "Göğüs ağrısı", aciklama: "Karakter ve yayılım", kategori: "Sikayet" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Eforla mı?", kategori: "Sikayet" },
      { key: "ONSET", etiket: "Başlangıç", aciklama: "Zamanlama", kategori: "HPI" },
      { key: "CARDIAC_RISK", etiket: "KV risk faktörleri", aciklama: "HT, DM, sigara", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Kullandığı ilaçlar", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "TROPONIN", etiket: "Troponin", aciklama: "Miyokart hasarı" },
      { key: "EKG", etiket: "EKG (12 derivasyon)", aciklama: "İskemi" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
    ],
    redFlagler: [{ key: "HEMODYNAMIC", etiket: "Hemodinamik bozulma", aciklama: "Şok" }],
    idealYol: [
      "1. 12 derivasyon EKG ve seri troponin iste.",
      "2. Risk skoru ile sınıflandır (TIMI / GRACE).",
      "3. Antitrombosit ve antikoagülasyonu başlat.",
      "4. Yüksek riskte erken invaziv strateji düşün.",
      "5. Kan basıncı ve kalp hızını yönet.",
      "6. Lipid yönetimi ve rehabilitasyonu planla.",
      "7. Kardiyoloji takibini düzenle.",
    ],
    egitimNotu: "NSTEMI: kalıcı ST elevasyonu olmadan troponin yükselişi. İnvaziv stratejiden önce risk sınıflandır.",
    anaSikayetStub: "Göğüs ağrısı",
    ozetStub: ["Göğüs ağrısı", "Eforla olabilir", "ST elevasyonu olmadan troponin yüksek"],
  },
  "kalp-yetmezligi": {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Eforla, ortopne?", kategori: "Sikayet" },
      { key: "EDEMA", etiket: "Ödem", aciklama: "Periferik şişlik", kategori: "Sikayet" },
      { key: "FATIGUE", etiket: "Yorgunluk", aciklama: "Efor kapasitesi", kategori: "Sistem" },
      { key: "CARDIAC_HISTORY", etiket: "Kardiyak öykü", aciklama: "KAH, MI", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Diüretik, beta-bloker", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "BNP", etiket: "BNP", aciklama: "Volüm yükü" },
      { key: "TROPONIN", etiket: "Troponin", aciklama: "Miyokart hasarı" },
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
      { key: "NA", etiket: "Sodyum", aciklama: "Elektrolitler" },
      { key: "K", etiket: "Potasyum", aciklama: "Elektrolitler" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
    ],
    redFlagler: [{ key: "HYPOXIA", etiket: "Hipoksi", aciklama: "Solunum sıkıntısı" }],
    idealYol: [
      "1. Oksijenasyon ve volüm durumunu değerlendir.",
      "2. BNP, troponin, böbrek ve elektrolit panelini iste.",
      "3. Gerekirse diüretik ve vazodilatör başla.",
      "4. Tetikleyici nedeni araştır.",
      "5. Sıvı dengesini ve kiloyu izle.",
      "6. Kılavuza uygun medikal tedaviyi optimize et.",
      "7. Kardiyoloji takibini planla.",
    ],
    egitimNotu: "Kalp yetmezliği: konjesyon + azalmış veya korunmuş ejeksiyon fraksiyonu. Önce volüm, sonra nedeni tedavi et.",
    anaSikayetStub: "Nefes darlığı",
    ozetStub: ["İlerleyici nefes darlığı", "Periferik ödem", "Ortopne olabilir"],
  },
  "atriyal-fibrilasyon": {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "PALPITATIONS", etiket: "Çarpıntı", aciklama: "Düzensiz ritim", kategori: "Sikayet" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Eforla mı?", kategori: "Sikayet" },
      { key: "ONSET", etiket: "Başlangıç", aciklama: "Paroksismal mi kalıcı mı", kategori: "HPI" },
      { key: "STROKE_RISK", etiket: "İnme riski", aciklama: "HT, DM, geçirilmiş inme", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Antikoagülasyon", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "EKG", etiket: "EKG (12 derivasyon)", aciklama: "Ritim" },
      { key: "TSH", etiket: "TSH", aciklama: "Tiroid nedeni" },
      { key: "K", etiket: "Potasyum", aciklama: "Elektrolitler" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
    ],
    redFlagler: [{ key: "HEMODYNAMIC", etiket: "Hemodinamik bozulma", aciklama: "Hızlı ventrikül yanıtı" }],
    idealYol: [
      "1. 12 derivasyon EKG ile ritmi doğrula.",
      "2. Hemodinamik stabiliteyi değerlendir.",
      "3. Ventrikül hızını kontrol et.",
      "4. İnme riskini hesapla (CHA2DS2-VASc).",
      "5. Gerekirse antikoagülasyon başla.",
      "6. Ritim kontrol stratejisini düşün.",
      "7. Takip ve izlemi düzenle.",
    ],
    egitimNotu: "Atriyal fibrilasyon: düzensiz düzensiz ritim. İnme koruması ile kanama riskini dengele.",
    anaSikayetStub: "Çarpıntı",
    ozetStub: ["Düzensiz kalp atışı", "Asemptomatik olabilir", "İnme riski değerlendirilmeli"],
  },
  "iskemik-kalp-hastaligi": {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "CHEST_PAIN", etiket: "Göğüs ağrısı", aciklama: "Eforla anjina", kategori: "Sikayet" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Eforla mı?", kategori: "Sikayet" },
      { key: "CARDIAC_RISK", etiket: "KV risk faktörleri", aciklama: "HT, DM, sigara", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Kullandığı ilaçlar", kategori: "Ilac" },
      { key: "FAMILY_HISTORY", etiket: "Aile öyküsü", aciklama: "Erken KAH", kategori: "Aile" },
    ],
    beklenenTestler: [
      { key: "CHOL", etiket: "Total kolesterol", aciklama: "Lipid paneli" },
      { key: "LDL", etiket: "LDL", aciklama: "Lipid paneli" },
      { key: "HDL", etiket: "HDL", aciklama: "Lipid paneli" },
      { key: "TRIG", etiket: "Trigliserit", aciklama: "Lipid paneli" },
      { key: "GLUKOZ", etiket: "Glukoz", aciklama: "Diyabet taraması" },
      { key: "EKG", etiket: "EKG", aciklama: "İskemi" },
    ],
    redFlagler: [{ key: "ACS", etiket: "Akut koroner sendrom", aciklama: "İstirahat ağrısı" }],
    idealYol: [
      "1. Semptomları ve fonksiyonel kapasiteyi değerlendir.",
      "2. Lipid paneli ve diyabet taraması iste.",
      "3. Bazal EKG çek.",
      "4. Yaşam tarzı değişikliklerini öner.",
      "5. Gerekirse statin ve antitrombosit başla.",
      "6. Efor testi veya anjiyografiyi düşün.",
      "7. Uzun dönem takibi planla.",
    ],
    egitimNotu: "İskemik kalp hastalığı: kronik koroner sendrom. İkincil koruma önceliklidir.",
    anaSikayetStub: "Eforla göğüs ağrısı",
    ozetStub: ["Eforla göğüs ağrısı", "KV risk faktörleri", "Dinlenince geçer"],
  },
  hipertansiyon: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "HEADACHE", etiket: "Baş ağrısı", aciklama: "Yeni başlangıç mı?", kategori: "Sikayet" },
      { key: "VISION", etiket: "Görme değişiklikleri", aciklama: "Bulanık görme?", kategori: "Sikayet" },
      { key: "LIFESTYLE", etiket: "Yaşam tarzı", aciklama: "Tuz, alkol, egzersiz", kategori: "Sosyal" },
      { key: "COMORBIDITIES", etiket: "Komorbiditeler", aciklama: "DM, KBH", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "Kullandığı ilaçlar", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
      { key: "NA", etiket: "Sodyum", aciklama: "Elektrolitler" },
      { key: "K", etiket: "Potasyum", aciklama: "Elektrolitler" },
      { key: "GLUKOZ", etiket: "Glukoz", aciklama: "Metabolik" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
      { key: "EKG", etiket: "EKG", aciklama: "SVH" },
    ],
    redFlagler: [{ key: "HYPERTENSIVE_CRISIS", etiket: "Hipertansif kriz", aciklama: "Hedef organ hasarı" }],
    idealYol: [
      "1. Tekrarlanan ölçümle yüksek kan basıncını doğrula.",
      "2. Hedef organ hasarını değerlendir.",
      "3. Böbrek, elektrolit ve metabolik paneli iste.",
      "4. Bazal EKG çek.",
      "5. Yaşam tarzı değişikliği öner.",
      "6. Antihipertansif tedavi başla.",
      "7. Titrasyon için takip planla.",
    ],
    egitimNotu: "Hipertansiyon: doğrula, hedef organ hasarını değerlendir, yaşam tarzı ve ilaçla tedavi et.",
    anaSikayetStub: "Yüksek kan basıncı",
    ozetStub: ["Çoğunlukla asemptomatik", "Rutin kontrolde saptanır", "Hedef organ hasarı değerlendirilmeli"],
  },
  "tip-2-diyabet": {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "POLYURIA", etiket: "Poliüri", aciklama: "Sık idrara çıkma", kategori: "Sikayet" },
      { key: "POLYDIPSIA", etiket: "Polidipsi", aciklama: "Aşırı susama", kategori: "Sikayet" },
      { key: "WEIGHT_CHANGE", etiket: "Kilo değişimi", aciklama: "Kayıp veya alım", kategori: "Sikayet" },
      { key: "DIABETES_HISTORY", etiket: "Diyabet öyküsü", aciklama: "Tanı ve ilaçlar", kategori: "Ozgecmis" },
      { key: "FOOT_SYMPTOMS", etiket: "Ayak yakınmaları", aciklama: "Nöropati", kategori: "Sistem" },
    ],
    beklenenTestler: [
      { key: "GLUKOZ", etiket: "Glukoz", aciklama: "Hiperglisemi" },
      { key: "HBA1C", etiket: "HbA1c", aciklama: "Uzun dönem kontrol" },
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
      { key: "GFR", etiket: "eGFR", aciklama: "Böbrek fonksiyonu" },
      { key: "U_PROTEIN", etiket: "İdrar proteini", aciklama: "Nefropati" },
    ],
    redFlagler: [
      { key: "DKA", etiket: "DKA bulguları", aciklama: "Kusma, bilinç değişikliği" },
      { key: "HYPOGLYCEMIA", etiket: "Hipoglisemi", aciklama: "Titreme, terleme" },
    ],
    idealYol: [
      "1. Glukoz ve HbA1c ile tanıyı doğrula.",
      "2. Komplikasyonları değerlendir (böbrek, göz, ayak).",
      "3. Böbrek paneli ve idrar proteinini iste.",
      "4. Diyet ve yaşam tarzı danışmanlığı ver.",
      "5. Metformin temelli tedavi başla.",
      "6. Kardiyovasküler riski tara.",
      "7. Multidisipliner takibi düzenle.",
    ],
    egitimNotu: "Tip 2 diyabet: tanı için HbA1c ve açlık glukozu. Mikrovasküler komplikasyonları tara.",
    anaSikayetStub: "Poliüri ve polidipsi",
    ozetStub: ["Poliüri / polidipsi", "Yorgunluk", "Bilinen veya yeni tanı diyabet"],
  },
  kbh: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "EDEMA", etiket: "Ödem", aciklama: "Şişlik başlangıcı", kategori: "Sikayet" },
      { key: "HTN_HISTORY", etiket: "Hipertansiyon", aciklama: "Öykü", kategori: "Ozgecmis" },
      { key: "DIABETES", etiket: "Diyabet", aciklama: "Öykü", kategori: "Ozgecmis" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "NSAİİ, ACE inhibitörü", kategori: "Ilac" },
      { key: "URINARY", etiket: "İdrar yakınmaları", aciklama: "Çıkış değişiklikleri", kategori: "Sistem" },
    ],
    beklenenTestler: [
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "GFR" },
      { key: "URE", etiket: "Üre", aciklama: "Azotemi" },
      { key: "GFR", etiket: "eGFR", aciklama: "Evreleme" },
      { key: "NA", etiket: "Sodyum", aciklama: "Elektrolitler" },
      { key: "K", etiket: "Potasyum", aciklama: "Elektrolitler" },
      { key: "U_PROTEIN", etiket: "İdrar proteini", aciklama: "Proteinüri" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "KBH anemisi" },
    ],
    redFlagler: [{ key: "HYPERKALEMIA", etiket: "Hiperkalemi", aciklama: "EKG değişiklikleri" }],
    idealYol: [
      "1. Üre, kreatinin, elektrolit ve idrar proteinini iste.",
      "2. eGFR ile evrele.",
      "3. Komplikasyonları değerlendir (anemi, kemik hastalığı).",
      "4. Kan basıncını kontrol et.",
      "5. Nefrotoksiklerden kaçın.",
      "6. Nefroprotektif tedavi ver.",
      "7. Nefrolojiye yönlendir.",
    ],
    egitimNotu: "KBH: 3 aydan uzun GFR düşüklüğü veya yapısal hasar. İzle ve ilerlemeyi yavaşlat.",
    anaSikayetStub: "Ödem ve yorgunluk",
    ozetStub: ["Ödem", "HT / DM komorbiditesi", "Proteinüri olabilir"],
  },
  pnomoni: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "COUGH", etiket: "Öksürük", aciklama: "Balgamlı mı?", kategori: "Sikayet" },
      { key: "FEVER", etiket: "Ateş", aciklama: "Süre", kategori: "Sikayet" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Efor kapasitesi", kategori: "Sikayet" },
      { key: "SMOKING", etiket: "Sigara", aciklama: "Paket-yıl", kategori: "Sosyal" },
      { key: "IMMUNOSUPPRESSION", etiket: "Bağışıklık durumu", aciklama: "Risk faktörleri", kategori: "Ozgecmis" },
    ],
    beklenenTestler: [
      { key: "WBC", etiket: "Lökosit", aciklama: "Lökositoz" },
      { key: "CRP", etiket: "CRP", aciklama: "Enflamasyon" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
      { key: "AKCIGER_GRAFISI", etiket: "Akciğer grafisi", aciklama: "İnfiltrasyon" },
    ],
    redFlagler: [
      { key: "RESPIRATORY_FAILURE", etiket: "Solunum yetmezliği", aciklama: "Düşük SpO2" },
      { key: "SEPSIS", etiket: "Sepsis", aciklama: "Hipotansiyon, laktat" },
    ],
    idealYol: [
      "1. Oksijenasyon ve vital bulguları değerlendir.",
      "2. Akciğer grafisi, hemogram ve CRP iste.",
      "3. Risk skoruyla sınıflandır (CURB-65).",
      "4. Ampirik antibiyotik başla.",
      "5. Destek tedavisi ver.",
      "6. 48-72 saat içinde yanıtı değerlendir.",
      "7. Gerekirse takip görüntülemesi planla.",
    ],
    egitimNotu: "Toplum kaynaklı pnömoni: klinik + radyolojik tanı. Bakım yerini belirlemek için ciddiyeti sınıflandır.",
    anaSikayetStub: "Öksürük, ateş, nefes darlığı",
    ozetStub: ["Balgamlı öksürük", "Ateş", "Plöritik ağrı olabilir"],
  },
  koah: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "İlerleyici mi?", kategori: "Sikayet" },
      { key: "COUGH", etiket: "Öksürük", aciklama: "Kronik balgam", kategori: "Sikayet" },
      { key: "SMOKING", etiket: "Sigara", aciklama: "Paket-yıl", kategori: "Sosyal" },
      { key: "EXACERBATIONS", etiket: "Alevlenmeler", aciklama: "Sıklığı", kategori: "HPI" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "İnhalerler", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "PH", etiket: "pH", aciklama: "ABG" },
      { key: "PCO2", etiket: "pCO2", aciklama: "ABG" },
      { key: "PO2", etiket: "pO2", aciklama: "ABG" },
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Hemogram" },
      { key: "WBC", etiket: "Lökosit", aciklama: "Enfeksiyon" },
      { key: "AKCIGER_GRAFISI", etiket: "Akciğer grafisi", aciklama: "Hiperinflasyon" },
    ],
    redFlagler: [{ key: "RESPIRATORY_FAILURE", etiket: "Solunum yetmezliği", aciklama: "CO2 retansiyonu" }],
    idealYol: [
      "1. Solunum durumu ve oksijenasyonu değerlendir.",
      "2. ABG ve akciğer grafisi iste.",
      "3. Bronkodilatör uygula.",
      "4. Sistemik steroid düşün.",
      "5. Enfeksiyon varsa tedavi et.",
      "6. Hiperkapnik yetmezliği izle.",
      "7. İdame inhaler ve sigara bırakmayı optimize et.",
    ],
    egitimNotu: "KOAH: alevlenmelerle seyreden kronik hava yolu kısıtlılığı. CO2 tutucularda oksijen hedefi dikkatli olmalı.",
    anaSikayetStub: "İlerleyici nefes darlığı",
    ozetStub: ["Kronik öksürük ve balgam", "Sigara öyküsü", "Artan nefes darlığı"],
  },
  astim: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "WHEEZE", etiket: "Hışıltı", aciklama: "Ataklar halinde mi?", kategori: "Sikayet" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Tetikleyiciler", kategori: "Sikayet" },
      { key: "NIGHT_SYMPTOMS", etiket: "Gece belirtileri", aciklama: "Gece uyanma", kategori: "HPI" },
      { key: "TRIGGERS", etiket: "Tetikleyiciler", aciklama: "Alerjen, egzersiz", kategori: "Sosyal" },
      { key: "MEDICATIONS", etiket: "İlaçlar", aciklama: "İnhalerler", kategori: "Ilac" },
    ],
    beklenenTestler: [
      { key: "PH", etiket: "pH", aciklama: "ABG" },
      { key: "PCO2", etiket: "pCO2", aciklama: "ABG" },
      { key: "PO2", etiket: "pO2", aciklama: "ABG" },
      { key: "WBC", etiket: "Lökosit", aciklama: "Hemogram" },
      { key: "EOS", etiket: "Eozinofil", aciklama: "Alerjik bileşen" },
    ],
    redFlagler: [{ key: "RESPIRATORY_FAILURE", etiket: "Solunum yetmezliği", aciklama: "Sessiz akciğer" }],
    idealYol: [
      "1. Ciddiyeti ve oksijenasyonu değerlendir.",
      "2. İnhale bronkodilatör uygula.",
      "3. Ciddiyse ABG iste.",
      "4. Sistemik steroid düşün.",
      "5. Tetikleyicileri belirle ve kaçın.",
      "6. Kontrol tedavisini optimize et.",
      "7. Astım eylem planı ver.",
    ],
    egitimNotu: "Astım: geri dönüşlü hava yolu obstrüksiyonu. Kontrolü değerlendir ve alevlenmeleri önleyecek şekilde tedavi et.",
    anaSikayetStub: "Hışıltı ve nefes darlığı",
    ozetStub: ["Ataklar halinde hışıltı", "Tetikleyici ile ilişkili", "Geri dönüşlü obstrüksiyon"],
  },
  iye: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "DYSURIA", etiket: "Dizüri", aciklama: "İdrarda yanma", kategori: "Sikayet" },
      { key: "FREQUENCY", etiket: "Sık idrar", aciklama: "İdrar aciliyeti", kategori: "Sikayet" },
      { key: "FEVER", etiket: "Ateş", aciklama: "Sistemik belirtiler", kategori: "Sikayet" },
      { key: "URINARY_HISTORY", etiket: "İdrar öyküsü", aciklama: "Tekrarlar", kategori: "Ozgecmis" },
      { key: "PREGNANCY", etiket: "Gebelik durumu", aciklama: "Kadınsa", kategori: "Sosyal" },
    ],
    beklenenTestler: [
      { key: "U_PH", etiket: "İdrar pH", aciklama: "İdrar tetkiki" },
      { key: "U_SG", etiket: "İdrar dansitesi", aciklama: "İdrar tetkiki" },
      { key: "U_PROTEIN", etiket: "İdrar proteini", aciklama: "İdrar tetkiki" },
      { key: "WBC", etiket: "Lökosit", aciklama: "Enfeksiyon" },
      { key: "CRP", etiket: "CRP", aciklama: "Enflamasyon" },
      { key: "KREATININ", etiket: "Kreatinin", aciklama: "Böbrek fonksiyonu" },
    ],
    redFlagler: [{ key: "PYELONEPHRITIS", etiket: "Piyelonefrit", aciklama: "Yan ağrısı, yüksek ateş" }],
    idealYol: [
      "1. İdrar yakınmalarını doğrula.",
      "2. İdrar tetkiki ve kültür iste.",
      "3. Sistemik tutulumu değerlendir.",
      "4. Ampirik antibiyotik başla.",
      "5. Yeterli hidrasyonu sağla.",
      "6. Kültür sonucuna göre tedaviyi düzenle.",
      "7. Korunma danışmanlığı ver.",
    ],
    egitimNotu: "İYE: dizüri ve sık idrar. Komplike olmayan sistiti piyelonefritten ayır.",
    anaSikayetStub: "Dizüri ve sık idrar",
    ozetStub: ["İdrarda yanma", "Sık idrara çıkma", "Sistitte sistemik bulgu yok"],
  },
  anemi: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "FATIGUE", etiket: "Yorgunluk", aciklama: "Başlangıç ve ciddiyet", kategori: "Sikayet" },
      { key: "DYSPNEA", etiket: "Nefes darlığı", aciklama: "Eforla mı?", kategori: "Sikayet" },
      { key: "BLEEDING", etiket: "Kanama öyküsü", aciklama: "GİS, adet", kategori: "HPI" },
      { key: "DIET", etiket: "Beslenme", aciklama: "Demir alımı", kategori: "Sosyal" },
      { key: "CHRONIC_DISEASE", etiket: "Kronik hastalık", aciklama: "KBH, enflamasyon", kategori: "Ozgecmis" },
    ],
    beklenenTestler: [
      { key: "HGB", etiket: "Hemoglobin", aciklama: "Anemi" },
      { key: "HCT", etiket: "Hematokrit", aciklama: "Anemi" },
      { key: "MCV", etiket: "MCV", aciklama: "Sınıflandırma" },
      { key: "RBC", etiket: "Eritrosit", aciklama: "Hemogram" },
      { key: "FERITIN", etiket: "Ferritin", aciklama: "Demir depoları" },
    ],
    redFlagler: [{ key: "ACTIVE_BLEEDING", etiket: "Aktif kanama", aciklama: "Hemodinamik bozulma" }],
    idealYol: [
      "1. Hemogramda anemiyi doğrula.",
      "2. MCV ile sınıflandır.",
      "3. Ferritin ve demir parametrelerini iste.",
      "4. Altta yatan nedeni araştır.",
      "5. Aktif kan kaybını değerlendir.",
      "6. Nedeni tedavi et (demir replasmanı).",
      "7. Tedavi yanıtını izle.",
    ],
    egitimNotu: "Anemi: MCV ile sınıflandır, demir depolarını araştır ve altta yatan nedeni tedavi et.",
    anaSikayetStub: "Yorgunluk",
    ozetStub: ["Yorgunluk", "Solukluk", "Eforla nefes darlığı"],
  },
  sinuzit: {
    ...DEFAULT_TEMPLATE,
    beklenenSorular: [
      { key: "NASAL", etiket: "Burun tıkanıklığı", aciklama: "Akıntı", kategori: "Sikayet" },
      { key: "FACIAL_PAIN", etiket: "Yüz ağrısı", aciklama: "Basınç", kategori: "Sikayet" },
      { key: "FEVER", etiket: "Ateş", aciklama: "Süre", kategori: "Sikayet" },
      { key: "DURATION", etiket: "Süre", aciklama: "Akut mu kronik mi", kategori: "HPI" },
      { key: "ALLERGIES", etiket: "Alerjiler", aciklama: "Atopi", kategori: "Ozgecmis" },
    ],
    beklenenTestler: [
      { key: "WBC", etiket: "Lökosit", aciklama: "Enfeksiyon" },
      { key: "CRP", etiket: "CRP", aciklama: "Enflamasyon" },
    ],
    redFlagler: [{ key: "ORBITAL", etiket: "Orbital komplikasyon", aciklama: "Proptozis, görme değişikliği" }],
    idealYol: [
      "1. Belirtileri ve süreyi değerlendir.",
      "2. Komplikasyonları muayene et.",
      "3. Antibiyotiği bakteriyel bulgulara sakla.",
      "4. Semptomatik tedavi öner.",
      "5. Komplike ise görüntüleme düşün.",
      "6. Altta yatan alerjiyi ele al.",
      "7. Kalıcı belirtiler için takip et.",
    ],
    egitimNotu: "Sinüzit: çoğunlukla viral. Antibiyotik kalıcı veya ciddi bakteriyel bulgularda.",
    anaSikayetStub: "Burun tıkanıklığı ve yüz ağrısı",
    ozetStub: ["Burun akıntısı", "Yüzde basınç", "Çoğunlukla viral"],
  },
};

export function getSyntheaRubricTemplate(hastalikKey: string): SyntheaRubricTemplate {
  return SYNTHEA_DISEASE_RUBRIC_TEMPLATES[hastalikKey] || DEFAULT_TEMPLATE;
}
