import { TipAiCdmDocument, TIP_AI_CDM_VERSION, DEFAULT_CDM_PUANLAMA } from "./types";

/** TIP-AI CDM v1 örnek: Kronik Böbrek Hastalığı (yazar şablonu) */
export const EXAMPLE_CDM_KBH: TipAiCdmDocument = {
  cdmVersion: TIP_AI_CDM_VERSION,
  id: "nefroloji::kronik-bobrek-hastaligi",
  meta: {
    poliklinikKey: "nefroloji",
    poliklinikAd: "Nefroloji",
    poliklinikIcon: "🫘",
    poliklinikAciklama: "Böbrek hastalıkları",
    hastalikKey: "kronik-bobrek-hastaligi",
    hastalikAdi: "Kronik Böbrek Hastalığı (KBH)",
    seviye: "orta",
    durum: "aktif",
    etiketler: ["Poliklinik", "Orta seviye"],
    surum: 1,
    uzmanOnayi: false,
  },
  patient: {
    yasAraligi: [45, 70],
    cinsiyetTercih: "herhangi",
    profil: {
      bmi: 28,
      sigara: "Eski içici",
      komorbiditeler: ["HTN", "T2DM"],
    },
  },
  presentation: {
    anaSikayet: "Yüz ve bacaklarda şişlik, köpüklü idrar",
    ozetBilgiler: [
      "1 haftadır yüzde ve bacaklarda şişlik",
      "Bacaklarda gode bırakan ödem",
      "İdrar köpüklü",
      "Kilo artışı (sıvıdan)",
    ],
    semptomSablon: "{{yas}} yaş {{cinsiyet}}, yüzde ve bacaklarda şişlik, köpüklü idrar",
  },
  conditions: [
    { code: "CKD_G3", ad: "Kronik Böbrek Hastalığı Evre 3", system: "local", primary: true },
    { code: "HTN", ad: "Esansiyel Hipertansiyon", system: "local" },
    { code: "T2DM", ad: "Tip 2 Diabetes Mellitus", system: "local" },
  ],
  rubric: {
    beklenenSorular: [
      {
        key: "ODEM_SURE",
        kategori: "Sikayet",
        etiket: "Ödem süresi",
        aciklama: "Ne zamandır şişlik var?",
      },
      {
        key: "IDRAR_KOPUK",
        kategori: "Sikayet",
        etiket: "Köpüklü idrar",
        aciklama: "İdrarınız köpüklü mü?",
      },
      {
        key: "HTN_OYKUSU",
        kategori: "Ozgecmis",
        etiket: "Hipertansiyon",
        aciklama: "HTN öyküsü",
      },
      {
        key: "DIYABET",
        kategori: "Ozgecmis",
        etiket: "Diyabet",
        aciklama: "DM öyküsü",
      },
      {
        key: "ILAC_KULLANIM",
        kategori: "Ilac",
        etiket: "İlaçlar",
        aciklama: "ACEi, NSAID vb.",
      },
      {
        key: "AILE_BOBREK",
        kategori: "Aile",
        etiket: "Ailede böbrek hastalığı",
        aciklama: "Ailede kronik böbrek hastalığı öyküsü",
      },
      {
        key: "SIGARA_ALKOL",
        kategori: "Sosyal",
        etiket: "Sigara ve alkol",
        aciklama: "Sigara ve alkol kullanım öyküsü",
      },
      {
        key: "NEFES_DARLIGI",
        kategori: "Sistem",
        etiket: "Nefes darlığı",
        aciklama: "Sıvı yükü veya kardiyopulmoner eşlik açısından sorgulama",
      },
    ],
    beklenenTestler: [
      { key: "KREATININ", etiket: "Serum kreatinin", aciklama: "Böbrek fonksiyonu" },
      { key: "URE", etiket: "Kan üre", aciklama: "Azotlu atık" },
      { key: "ELEKTROLIT", etiket: "Na/K", aciklama: "Elektrolitler" },
      { key: "IDRAR", etiket: "Tam idrar tetkiki", aciklama: "Proteinüri" },
    ],
    gereksizTestler: [
      { key: "BT_TORAKS", etiket: "BT Toraks", aciklama: "İlk basamakta gereksiz" },
    ],
    redFlagler: [
      {
        key: "HIPERKALEMI",
        etiket: "Hiperkalemi bulguları",
        aciklama: "EKG değişikliği, kas güçsüzlüğü",
      },
      {
        key: "AKI",
        etiket: "Akut kötüleşme",
        aciklama: "Akut böbrek hasarı bulguları",
      },
    ],
    kabulEdilenTani: [
      "Kronik Böbrek Hastalığı",
      "KBH Evre 3",
      "KBH Evre 4",
    ],
    puanlama: { ...DEFAULT_CDM_PUANLAMA },
  },
  labs: {
    statikTestler: {
      KREATININ: {
        testKey: "KREATININ",
        testAdi: "Serum kreatinin",
        tip: "numeric",
        sonuc: { deger: 2.1, birim: "mg/dL", referansAralik: "0.6-1.2" },
        referans: "Lab",
        yorum: "Yüksek — KBH ile uyumlu.",
        flag: "high",
      },
      URE: {
        testKey: "URE",
        testAdi: "Kan Üre",
        tip: "numeric",
        sonuc: { deger: 65, birim: "mg/dL", referansAralik: "10-50" },
        referans: "Lab",
        yorum: "Yüksek — renal fonksiyon bozukluğu.",
        flag: "high",
      },
      ELEKTROLIT: {
        testKey: "ELEKTROLIT",
        testAdi: "Elektrolitler",
        tip: "json",
        sonuc: { sodyum: "138 mmol/L", potasyum: "5.4 mmol/L" },
        referans: "Lab",
        yorum: "Sodyum normal, potasyum hafif yüksek.",
        flag: "abnormal",
      },
      IDRAR: {
        testKey: "IDRAR",
        testAdi: "Tam idrar tetkiki",
        tip: "json",
        sonuc: { protein: "3+", eritrosit: "1-2 /hpf" },
        referans: "Lab",
        yorum: "Ağır proteinüri.",
        flag: "abnormal",
      },
      CBC: {
        testKey: "CBC",
        testAdi: "Hemogram",
        tip: "json",
        sonuc: { hemoglobin: "10.5 g/dL", lokosit: "7.8 K/uL" },
        referans: "Lab",
        yorum: "Hafif anemi, lökosit normal.",
        flag: "abnormal",
      },
    },
  },
  vitals: {
    tansiyon: "150/95",
    nabiz: 92,
    ates: 36.7,
    spo2: 96,
    solunum: 18,
  },
  hastaYanitlari: {
    ODEM_SURE: "Yaklaşık 1 haftadır",
    IDRAR_KOPUK: "Evet, son günlerde daha köpüklü",
    HTN_OYKUSU: "10 yıldır hipertansiyonum var",
    DIYABET: "5 yıldır tip 2 diyabetim var",
    ILAC_KULLANIM: "Amlodipin ve metformin kullanıyorum",
    AILE_BOBREK: "Ailemde bilinen böbrek hastalığı yok.",
    SIGARA_ALKOL: "10 yıl sigara içtim, 4 yıl önce bıraktım; alkolü nadiren kullanıyorum.",
    NEFES_DARLIGI: "İstirahatte nefes darlığım yok, merdiven çıkınca hafif yoruluyorum.",
    VITAL_TANSIYON: "150/95",
    VITAL_NABIZ: "92",
    VITAL_ATES: "36.7",
    VITAL_SPO2: "96",
    VITAL_SOLUNUM: "18",
    OZEL: "Anlamadım",
  },
  management: {
    idealYol: [
      "1. Ödemin süresini, idrar değişikliklerini, nefes darlığını ve akut kötüleşme bulgularını hedefli öykü ile değerlendir.",
      "2. Tansiyon, kilo, akciğer oskültasyonu ve periferik ödemi içeren fizik muayeneyi tamamla.",
      "3. Üre, kreatinin, eGFR, elektrolitler, hemogram ve tam idrar tetkikini iste.",
      "4. Proteinüriyi nicelleştir ve ilaç/NSAID kullanımını, diyabet ile hipertansiyon kontrolünü gözden geçir.",
      "5. KBH evresini GFR ve albuminüri ile değerlendir; akut böbrek hasarı ile ayırıcı tanıyı yap.",
      "6. Hiperkalemi, hızla azalan idrar çıkışı, pulmoner ödem ve EKG değişikliği gibi acil red flagleri dışla.",
      "7. Kan basıncı ve proteinüri için RAAS blokajını uygunluk açısından değerlendir; ödem tedavisini planla.",
      "8. Nefroloji takibi, tuz kısıtlaması, sıvı dengesi, ilaç güvenliği ve kontrol testleri için yazılı plan oluştur.",
    ],
    egitimNotu:
      "Kronik böbrek hastalığı, böbrek fonksiyonunda veya böbrek yapısında en az üç ay süren bozulma ile tanımlanır. eGFR değerinin 60 mL/dk/1,73 m² altında olması, kalıcı albuminüri ya da idrar sedimentinde anormallik tanıya destek verir. Bu vakada ödem, köpüklü idrar, kreatinin yüksekliği ve proteinüri böbrek hasarı ile uyumludur. Değerlendirmede yalnız kreatinine değil; eGFR, potasyum, bikarbonat, hemoglobin, idrar tahlili ve albumin/kreatinin oranına birlikte bakılmalıdır. Ani kreatinin artışı, oligüri, ciddi hiperkalemi, akciğer ödemi veya bilinç değişikliği acil değerlendirme gerektirir. Tedavinin temel hedefleri kan basıncını ve diyabeti iyi kontrol etmek, albuminürisi olan uygun hastalarda RAAS blokajını değerlendirmek, tuz tüketimini azaltmak ve böbreğe zarar verebilen NSAID gibi ilaçlardan kaçınmaktır. Ödemde sıvı dengesi, günlük kilo takibi ve gerektiğinde diüretik tedavisi planlanır. ACE inhibitörü veya ARB başlandıktan ya da dozu değiştirildikten sonra kreatinin ve potasyum erken dönemde yeniden kontrol edilmelidir. Hastaya ilaçlarını reçete dışı kesmemesi, dehidratasyondan kaçınması ve kontrol randevularını aksatmaması anlatılmalıdır. Evde hızla artan nefes darlığı, göğüs ağrısı, belirgin çarpıntı, idrar miktarında azalma veya hızla artan şişlik gelişirse gecikmeden sağlık kuruluşuna başvurması gerektiği açıkça belirtilmelidir. Nefroloji izlemi, hastalığın evresine ve albuminüri düzeyine göre böbrek replasman tedavisine hazırlık zamanlamasını da güvenli biçimde belirler. Aşılar, kardiyovasküler risk, beslenme desteği ve ilaç dozlarının böbrek fonksiyonuna göre ayarlanması her kontrolde yeniden gözden geçirilmelidir.",
    tedavi: {
      ilaclar: [
        {
          ad: "ACE inhibitörü (ör. Ramipril)",
          doz: "5 mg/gün",
          yol: "PO",
          siklik: "Günde 1 kez",
          sure: "Uzun dönem; 1–2 hafta sonra kreatinin ve potasyum kontrolü",
          endikasyon: "Proteinürili KBH ve HTN",
        },
        {
          ad: "Loop diüretik (ör. Furosemid)",
          doz: "40 mg/gün",
          yol: "PO",
          siklik: "Günde 1 kez; klinik yanıta göre",
          sure: "Ödem düzelene kadar, yakın klinik takip ile",
          endikasyon: "Ödem kontrolü",
        },
      ],
      prosedurler: [
        "Tuz kısıtlaması ve sıvı dengesi eğitimi",
        "Nefroloji polikliniğine düzenli kontrol planı",
      ],
      onemliNotlar: [
        "NSAID kullanımından kaçınılmalı.",
        "Hiperkalemi açısından ACEi/ARB kullanırken elektrolitler düzenli takip edilmeli.",
      ],
    },
  },
};
